name: Node.js Package and Docker publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      # Setup .npmrc file to publish to npm
      - name: Setup npm registry auth
        run: |
          echo "registry=https://registry.npmjs.org/" > "${HOME}/.npmrc"
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> "${HOME}/.npmrc"
      - name: Set tag version
        id: ref_tag
        run: echo "version=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Update package.json
        run: |
          pnpm version "${RELEASE_VERSION}" --no-git-tag-version --allow-same-version
        env:
          RELEASE_VERSION: ${{ steps.ref_tag.outputs.version }}
      - name: Commit updates
        uses: EndBug/add-and-commit@v9
        with:
          branch: master
          message: "Bump version: v${{ steps.ref_tag.outputs.version }}"
          add: "['package.json', 'README.md']"
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t keisuke6065/openapi-combine:$VERSION . --build-arg version=$VERSION
          docker tag keisuke6065/openapi-combine:$VERSION keisuke6065/openapi-combine:latest
          docker push keisuke6065/openapi-combine:$VERSION
          docker push keisuke6065/openapi-combine:latest
        env:
          VERSION: ${{ steps.ref_tag.outputs.version }}
