name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        if: github.event_name == 'push'
        uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label pull request
        if: github.event_name == 'pull_request'
        uses: release-drafter/release-drafter/autolabeler@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
